version: '3.8'

services:
  db:
    image: postgres:16
    container_name: blog-amplix-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: